version: '3.7'

volumes:
  l1_data:
  l2_data:
  op_log:

services:
  l1:
    build:
      context: .
      dockerfile: Dockerfile.l1
    stop_signal: SIGINT
    stop_grace_period: 30s
    ports:
      - "8545:8545"
      - "7060:6060"
    volumes:
      - "l1_data:/db/.syscoin"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 192.168.9.45
    deploy:
      restart_policy:
        condition: on-failure

  l2:
    build:
      context: .
      dockerfile: Dockerfile.l2
    stop_signal: SIGINT
    stop_grace_period: 30s
    ports:
      - "9545:8545"
      - "9546:8546"
      - "8060:6060"
      - "30303:30303"
    volumes:
      - "l2_data:/db"
      - "${PWD}/../.devnet/genesis-l2.json:/genesis.json"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
    entrypoint:
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/test-jwt-secret.txt"
    env_file:
      - ./envs/p2p-node.env
    deploy:
      restart_policy:
        condition: on-failure

  op-node:
    build:
      context: ../
      dockerfile: ./op-node/Dockerfile
    stop_signal: SIGINT
    stop_grace_period: 30s
    command: >
      op-node
      --l1=ws://l1:8546
      --l2=http://l2:9551
      --l2.jwt-secret=/config/test-jwt-secret.txt
      --sequencer.stopped
      --sequencer.l1-confs=0
      --verifier.l1-confs=0
      --rollup.config=/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8545
      --p2p.no-discovery=false
      --p2p.listen.ip=0.0.0.0
      --p2p.listen.tcp=9003
      --p2p.listen.udp=9003
      --p2p.static=/ip4/<ip>/tcp/9003/p2p/<peer_ids>
      --snapshotlog.file=/op_log/snapshot.log
      --p2p.priv.path=/config/p2p-node-key.txt
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --pprof.enabled
      --rpc.enable-admin
      --heartbeat.enabled
      --heartbeat.moniker=sequencer
      --heartbeat.url=http://op-heartbeat:8080
    ports:
      - "7545:8545"
      - "9003:9003"
      - "7300:7300"
      - "6060:6060"
    volumes:
      - "${PWD}/p2p-node-key.txt:/config/p2p-node-key.txt"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
      - "${PWD}/../.devnet/rollup.json:/rollup.json"
      - op_log:/op_log
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 192.168.9.45
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s

networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
